//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFFudbal.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwIgrac", Namespace="http://schemas.datacontract.org/2004/07/WCFSERVICEFSS")]
    [System.SerializableAttribute()]
    public partial class vwIgrac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nacionalnostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazTimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int timField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string datum {
            get {
                return this.datumField;
            }
            set {
                if ((object.ReferenceEquals(this.datumField, value) != true)) {
                    this.datumField = value;
                    this.RaisePropertyChanged("datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ime {
            get {
                return this.imeField;
            }
            set {
                if ((object.ReferenceEquals(this.imeField, value) != true)) {
                    this.imeField = value;
                    this.RaisePropertyChanged("ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nacionalnost {
            get {
                return this.nacionalnostField;
            }
            set {
                if ((this.nacionalnostField.Equals(value) != true)) {
                    this.nacionalnostField = value;
                    this.RaisePropertyChanged("nacionalnost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazNac {
            get {
                return this.nazNacField;
            }
            set {
                if ((object.ReferenceEquals(this.nazNacField, value) != true)) {
                    this.nazNacField = value;
                    this.RaisePropertyChanged("nazNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazTim {
            get {
                return this.nazTimField;
            }
            set {
                if ((object.ReferenceEquals(this.nazTimField, value) != true)) {
                    this.nazTimField = value;
                    this.RaisePropertyChanged("nazTim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prezime {
            get {
                return this.prezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.prezimeField, value) != true)) {
                    this.prezimeField = value;
                    this.RaisePropertyChanged("prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tim {
            get {
                return this.timField;
            }
            set {
                if ((this.timField.Equals(value) != true)) {
                    this.timField = value;
                    this.RaisePropertyChanged("tim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwTim", Namespace="http://schemas.datacontract.org/2004/07/WCFSERVICEFSS")]
    [System.SerializableAttribute()]
    public partial class vwTim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ligaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazLigeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string osnovanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sedisteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int liga {
            get {
                return this.ligaField;
            }
            set {
                if ((this.ligaField.Equals(value) != true)) {
                    this.ligaField = value;
                    this.RaisePropertyChanged("liga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazLige {
            get {
                return this.nazLigeField;
            }
            set {
                if ((object.ReferenceEquals(this.nazLigeField, value) != true)) {
                    this.nazLigeField = value;
                    this.RaisePropertyChanged("nazLige");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                if ((object.ReferenceEquals(this.nazivField, value) != true)) {
                    this.nazivField = value;
                    this.RaisePropertyChanged("naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string osnovan {
            get {
                return this.osnovanField;
            }
            set {
                if ((object.ReferenceEquals(this.osnovanField, value) != true)) {
                    this.osnovanField = value;
                    this.RaisePropertyChanged("osnovan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sediste {
            get {
                return this.sedisteField;
            }
            set {
                if ((object.ReferenceEquals(this.sedisteField, value) != true)) {
                    this.sedisteField = value;
                    this.RaisePropertyChanged("sediste");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwLiga", Namespace="http://schemas.datacontract.org/2004/07/WCFSERVICEFSS")]
    [System.SerializableAttribute()]
    public partial class vwLiga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazKatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oznakaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazKat {
            get {
                return this.nazKatField;
            }
            set {
                if ((object.ReferenceEquals(this.nazKatField, value) != true)) {
                    this.nazKatField = value;
                    this.RaisePropertyChanged("nazKat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                if ((object.ReferenceEquals(this.nazivField, value) != true)) {
                    this.nazivField = value;
                    this.RaisePropertyChanged("naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oznaka {
            get {
                return this.oznakaField;
            }
            set {
                if ((object.ReferenceEquals(this.oznakaField, value) != true)) {
                    this.oznakaField = value;
                    this.RaisePropertyChanged("oznaka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rang {
            get {
                return this.rangField;
            }
            set {
                if ((this.rangField.Equals(value) != true)) {
                    this.rangField = value;
                    this.RaisePropertyChanged("rang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwKategorija", Namespace="http://schemas.datacontract.org/2004/07/WCFSERVICEFSS")]
    [System.SerializableAttribute()]
    public partial class vwKategorija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Expr2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr1 {
            get {
                return this.Expr1Field;
            }
            set {
                if ((this.Expr1Field.Equals(value) != true)) {
                    this.Expr1Field = value;
                    this.RaisePropertyChanged("Expr1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expr2 {
            get {
                return this.Expr2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Expr2Field, value) != true)) {
                    this.Expr2Field = value;
                    this.RaisePropertyChanged("Expr2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rang {
            get {
                return this.rangField;
            }
            set {
                if ((object.ReferenceEquals(this.rangField, value) != true)) {
                    this.rangField = value;
                    this.RaisePropertyChanged("rang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwNacionalnost", Namespace="http://schemas.datacontract.org/2004/07/WCFSERVICEFSS")]
    [System.SerializableAttribute()]
    public partial class vwNacionalnost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Expr2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Expr3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skracenicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr1 {
            get {
                return this.Expr1Field;
            }
            set {
                if ((this.Expr1Field.Equals(value) != true)) {
                    this.Expr1Field = value;
                    this.RaisePropertyChanged("Expr1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expr2 {
            get {
                return this.Expr2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Expr2Field, value) != true)) {
                    this.Expr2Field = value;
                    this.RaisePropertyChanged("Expr2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expr3 {
            get {
                return this.Expr3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Expr3Field, value) != true)) {
                    this.Expr3Field = value;
                    this.RaisePropertyChanged("Expr3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                if ((object.ReferenceEquals(this.nazivField, value) != true)) {
                    this.nazivField = value;
                    this.RaisePropertyChanged("naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string skracenica {
            get {
                return this.skracenicaField;
            }
            set {
                if ((object.ReferenceEquals(this.skracenicaField, value) != true)) {
                    this.skracenicaField = value;
                    this.RaisePropertyChanged("skracenica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFSERVICEFSS")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IgracList", ReplyAction="http://tempuri.org/IService1/IgracListResponse")]
        WPFFudbal.ServiceReference1.vwIgrac[] IgracList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IgracList", ReplyAction="http://tempuri.org/IService1/IgracListResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwIgrac[]> IgracListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimList", ReplyAction="http://tempuri.org/IService1/TimListResponse")]
        WPFFudbal.ServiceReference1.vwTim[] TimList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimList", ReplyAction="http://tempuri.org/IService1/TimListResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwTim[]> TimListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LigaList", ReplyAction="http://tempuri.org/IService1/LigaListResponse")]
        WPFFudbal.ServiceReference1.vwLiga[] LigaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LigaList", ReplyAction="http://tempuri.org/IService1/LigaListResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwLiga[]> LigaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KategorijaList", ReplyAction="http://tempuri.org/IService1/KategorijaListResponse")]
        WPFFudbal.ServiceReference1.vwKategorija[] KategorijaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KategorijaList", ReplyAction="http://tempuri.org/IService1/KategorijaListResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwKategorija[]> KategorijaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NacionalnostList", ReplyAction="http://tempuri.org/IService1/NacionalnostListResponse")]
        WPFFudbal.ServiceReference1.vwNacionalnost[] NacionalnostList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NacionalnostList", ReplyAction="http://tempuri.org/IService1/NacionalnostListResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwNacionalnost[]> NacionalnostListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IgracAdd", ReplyAction="http://tempuri.org/IService1/IgracAddResponse")]
        WPFFudbal.ServiceReference1.vwIgrac IgracAdd(WPFFudbal.ServiceReference1.vwIgrac igrac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IgracAdd", ReplyAction="http://tempuri.org/IService1/IgracAddResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwIgrac> IgracAddAsync(WPFFudbal.ServiceReference1.vwIgrac igrac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimAdd", ReplyAction="http://tempuri.org/IService1/TimAddResponse")]
        WPFFudbal.ServiceReference1.vwTim TimAdd(WPFFudbal.ServiceReference1.vwTim tim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimAdd", ReplyAction="http://tempuri.org/IService1/TimAddResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwTim> TimAddAsync(WPFFudbal.ServiceReference1.vwTim tim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LigaAdd", ReplyAction="http://tempuri.org/IService1/LigaAddResponse")]
        WPFFudbal.ServiceReference1.vwLiga LigaAdd(WPFFudbal.ServiceReference1.vwLiga liga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LigaAdd", ReplyAction="http://tempuri.org/IService1/LigaAddResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwLiga> LigaAddAsync(WPFFudbal.ServiceReference1.vwLiga liga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KategorijaAdd", ReplyAction="http://tempuri.org/IService1/KategorijaAddResponse")]
        WPFFudbal.ServiceReference1.vwKategorija KategorijaAdd(WPFFudbal.ServiceReference1.vwKategorija kategorija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KategorijaAdd", ReplyAction="http://tempuri.org/IService1/KategorijaAddResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwKategorija> KategorijaAddAsync(WPFFudbal.ServiceReference1.vwKategorija kategorija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NacionalnostAdd", ReplyAction="http://tempuri.org/IService1/NacionalnostAddResponse")]
        WPFFudbal.ServiceReference1.vwNacionalnost NacionalnostAdd(WPFFudbal.ServiceReference1.vwNacionalnost nacionalnost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NacionalnostAdd", ReplyAction="http://tempuri.org/IService1/NacionalnostAddResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwNacionalnost> NacionalnostAddAsync(WPFFudbal.ServiceReference1.vwNacionalnost nacionalnost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IgracBrisanje", ReplyAction="http://tempuri.org/IService1/IgracBrisanjeResponse")]
        void IgracBrisanje(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IgracBrisanje", ReplyAction="http://tempuri.org/IService1/IgracBrisanjeResponse")]
        System.Threading.Tasks.Task IgracBrisanjeAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimBrisanje", ReplyAction="http://tempuri.org/IService1/TimBrisanjeResponse")]
        void TimBrisanje(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimBrisanje", ReplyAction="http://tempuri.org/IService1/TimBrisanjeResponse")]
        System.Threading.Tasks.Task TimBrisanjeAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KategorijaBrisanje", ReplyAction="http://tempuri.org/IService1/KategorijaBrisanjeResponse")]
        void KategorijaBrisanje(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KategorijaBrisanje", ReplyAction="http://tempuri.org/IService1/KategorijaBrisanjeResponse")]
        System.Threading.Tasks.Task KategorijaBrisanjeAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NacionalnostBrisanje", ReplyAction="http://tempuri.org/IService1/NacionalnostBrisanjeResponse")]
        void NacionalnostBrisanje(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NacionalnostBrisanje", ReplyAction="http://tempuri.org/IService1/NacionalnostBrisanjeResponse")]
        System.Threading.Tasks.Task NacionalnostBrisanjeAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LigaBrisanje", ReplyAction="http://tempuri.org/IService1/LigaBrisanjeResponse")]
        void LigaBrisanje(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LigaBrisanje", ReplyAction="http://tempuri.org/IService1/LigaBrisanjeResponse")]
        System.Threading.Tasks.Task LigaBrisanjeAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneIgrac", ReplyAction="http://tempuri.org/IService1/GetOneIgracResponse")]
        WPFFudbal.ServiceReference1.vwIgrac GetOneIgrac(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneIgrac", ReplyAction="http://tempuri.org/IService1/GetOneIgracResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwIgrac> GetOneIgracAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneKategorija", ReplyAction="http://tempuri.org/IService1/GetOneKategorijaResponse")]
        WPFFudbal.ServiceReference1.vwKategorija GetOneKategorija(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneKategorija", ReplyAction="http://tempuri.org/IService1/GetOneKategorijaResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwKategorija> GetOneKategorijaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneliga", ReplyAction="http://tempuri.org/IService1/GetOneligaResponse")]
        WPFFudbal.ServiceReference1.vwLiga GetOneliga(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneliga", ReplyAction="http://tempuri.org/IService1/GetOneligaResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwLiga> GetOneligaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneNacionalnost", ReplyAction="http://tempuri.org/IService1/GetOneNacionalnostResponse")]
        WPFFudbal.ServiceReference1.vwNacionalnost GetOneNacionalnost(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneNacionalnost", ReplyAction="http://tempuri.org/IService1/GetOneNacionalnostResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwNacionalnost> GetOneNacionalnostAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneTim", ReplyAction="http://tempuri.org/IService1/GetOneTimResponse")]
        WPFFudbal.ServiceReference1.vwTim GetOneTim(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneTim", ReplyAction="http://tempuri.org/IService1/GetOneTimResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwTim> GetOneTimAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WPFFudbal.ServiceReference1.CompositeType GetDataUsingDataContract(WPFFudbal.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WPFFudbal.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WPFFudbal.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WPFFudbal.ServiceReference1.IService1>, WPFFudbal.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFFudbal.ServiceReference1.vwIgrac[] IgracList() {
            return base.Channel.IgracList();
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwIgrac[]> IgracListAsync() {
            return base.Channel.IgracListAsync();
        }
        
        public WPFFudbal.ServiceReference1.vwTim[] TimList() {
            return base.Channel.TimList();
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwTim[]> TimListAsync() {
            return base.Channel.TimListAsync();
        }
        
        public WPFFudbal.ServiceReference1.vwLiga[] LigaList() {
            return base.Channel.LigaList();
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwLiga[]> LigaListAsync() {
            return base.Channel.LigaListAsync();
        }
        
        public WPFFudbal.ServiceReference1.vwKategorija[] KategorijaList() {
            return base.Channel.KategorijaList();
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwKategorija[]> KategorijaListAsync() {
            return base.Channel.KategorijaListAsync();
        }
        
        public WPFFudbal.ServiceReference1.vwNacionalnost[] NacionalnostList() {
            return base.Channel.NacionalnostList();
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwNacionalnost[]> NacionalnostListAsync() {
            return base.Channel.NacionalnostListAsync();
        }
        
        public WPFFudbal.ServiceReference1.vwIgrac IgracAdd(WPFFudbal.ServiceReference1.vwIgrac igrac) {
            return base.Channel.IgracAdd(igrac);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwIgrac> IgracAddAsync(WPFFudbal.ServiceReference1.vwIgrac igrac) {
            return base.Channel.IgracAddAsync(igrac);
        }
        
        public WPFFudbal.ServiceReference1.vwTim TimAdd(WPFFudbal.ServiceReference1.vwTim tim) {
            return base.Channel.TimAdd(tim);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwTim> TimAddAsync(WPFFudbal.ServiceReference1.vwTim tim) {
            return base.Channel.TimAddAsync(tim);
        }
        
        public WPFFudbal.ServiceReference1.vwLiga LigaAdd(WPFFudbal.ServiceReference1.vwLiga liga) {
            return base.Channel.LigaAdd(liga);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwLiga> LigaAddAsync(WPFFudbal.ServiceReference1.vwLiga liga) {
            return base.Channel.LigaAddAsync(liga);
        }
        
        public WPFFudbal.ServiceReference1.vwKategorija KategorijaAdd(WPFFudbal.ServiceReference1.vwKategorija kategorija) {
            return base.Channel.KategorijaAdd(kategorija);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwKategorija> KategorijaAddAsync(WPFFudbal.ServiceReference1.vwKategorija kategorija) {
            return base.Channel.KategorijaAddAsync(kategorija);
        }
        
        public WPFFudbal.ServiceReference1.vwNacionalnost NacionalnostAdd(WPFFudbal.ServiceReference1.vwNacionalnost nacionalnost) {
            return base.Channel.NacionalnostAdd(nacionalnost);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwNacionalnost> NacionalnostAddAsync(WPFFudbal.ServiceReference1.vwNacionalnost nacionalnost) {
            return base.Channel.NacionalnostAddAsync(nacionalnost);
        }
        
        public void IgracBrisanje(int ID) {
            base.Channel.IgracBrisanje(ID);
        }
        
        public System.Threading.Tasks.Task IgracBrisanjeAsync(int ID) {
            return base.Channel.IgracBrisanjeAsync(ID);
        }
        
        public void TimBrisanje(int ID) {
            base.Channel.TimBrisanje(ID);
        }
        
        public System.Threading.Tasks.Task TimBrisanjeAsync(int ID) {
            return base.Channel.TimBrisanjeAsync(ID);
        }
        
        public void KategorijaBrisanje(int ID) {
            base.Channel.KategorijaBrisanje(ID);
        }
        
        public System.Threading.Tasks.Task KategorijaBrisanjeAsync(int ID) {
            return base.Channel.KategorijaBrisanjeAsync(ID);
        }
        
        public void NacionalnostBrisanje(int ID) {
            base.Channel.NacionalnostBrisanje(ID);
        }
        
        public System.Threading.Tasks.Task NacionalnostBrisanjeAsync(int ID) {
            return base.Channel.NacionalnostBrisanjeAsync(ID);
        }
        
        public void LigaBrisanje(int ID) {
            base.Channel.LigaBrisanje(ID);
        }
        
        public System.Threading.Tasks.Task LigaBrisanjeAsync(int ID) {
            return base.Channel.LigaBrisanjeAsync(ID);
        }
        
        public WPFFudbal.ServiceReference1.vwIgrac GetOneIgrac(int ID) {
            return base.Channel.GetOneIgrac(ID);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwIgrac> GetOneIgracAsync(int ID) {
            return base.Channel.GetOneIgracAsync(ID);
        }
        
        public WPFFudbal.ServiceReference1.vwKategorija GetOneKategorija(int ID) {
            return base.Channel.GetOneKategorija(ID);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwKategorija> GetOneKategorijaAsync(int ID) {
            return base.Channel.GetOneKategorijaAsync(ID);
        }
        
        public WPFFudbal.ServiceReference1.vwLiga GetOneliga(int ID) {
            return base.Channel.GetOneliga(ID);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwLiga> GetOneligaAsync(int ID) {
            return base.Channel.GetOneligaAsync(ID);
        }
        
        public WPFFudbal.ServiceReference1.vwNacionalnost GetOneNacionalnost(int ID) {
            return base.Channel.GetOneNacionalnost(ID);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwNacionalnost> GetOneNacionalnostAsync(int ID) {
            return base.Channel.GetOneNacionalnostAsync(ID);
        }
        
        public WPFFudbal.ServiceReference1.vwTim GetOneTim(int ID) {
            return base.Channel.GetOneTim(ID);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.vwTim> GetOneTimAsync(int ID) {
            return base.Channel.GetOneTimAsync(ID);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WPFFudbal.ServiceReference1.CompositeType GetDataUsingDataContract(WPFFudbal.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WPFFudbal.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WPFFudbal.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
