//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSERVICEFSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIgrac
    {
        public int ID { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string datum { get; set; }
        public int tim { get; set; }
        public int nacionalnost { get; set; }
    
        public virtual tblNacionalnost tblNacionalnost { get; set; }
        public virtual tblTim tblTim { get; set; }
    }
}
