//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSERVICEFSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLiga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLiga()
        {
            this.tblTims = new HashSet<tblTim>();
        }
    
        public int ID { get; set; }
        public string naziv { get; set; }
        public string oznaka { get; set; }
        public int rang { get; set; }
    
        public virtual tblKategorija tblKategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTim> tblTims { get; set; }
    }
}
