//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSERVICEFSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLiga
    {
        public int ID { get; set; }
        public string naziv { get; set; }
        public string oznaka { get; set; }
        public int rang { get; set; }
        public string nazKat { get; set; }
    }
}
