//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSERVICEFSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwNacionalnost
    {
        public int ID { get; set; }
        public string naziv { get; set; }
        public string skracenica { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
    }
}
