//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSERVICEFSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTim
    {
        public int ID { get; set; }
        public string naziv { get; set; }
        public string sediste { get; set; }
        public string osnovan { get; set; }
        public int liga { get; set; }
        public string nazLige { get; set; }
    }
}
